services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:35.0.0
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloudpass
    volumes:
      - /home/robbo/docker/nextcloud/config:/config
      - /mnt/media/nextcloud/data:/data
    ports:
      - "4443:443"
    depends_on:
      - nextcloud_db
    networks:
      - nextcloud_net
    restart: unless-stopped

  nextcloud_db:
    image: mariadb:10.6
    container_name: nextcloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloudpass
    volumes:
      - /home/robbo/docker/nextcloud/db:/var/lib/mysql
    networks:
      - nextcloud_net
    restart: unless-stopped

networks:
  nextcloud_net:
    driver: bridge
