service:

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    ports:
      - "2283:2283"
    volumes:
      - ${UPLOAD_LOCATION}:/data
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # Changed from :release to the openvino variant
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino
    volumes:
      - model-cache:/cache
    restart: always


  redis:
    container_name: immich_redis
    image: valkey/valkey:latest
    restart: always

  database:
    container_name: immich_postgres
    image: pgvector/pgvector:pg14
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

    
networks:
  tv-network:
    driver: bridge
   - default     # Keeps it connected to its internal Postgres/Redis
   - proxy-tier  # Allows your reverse proxy to see it

volumes:
  ollama-data:
  open-webui-data:
  model-cache:
  pgdata:
  redisdata:
  paperless_consume:
    driver: local
    driver_opts:
      type: cifs
#      o: "username=robbo,password=atilla1atilla1,uid=1000,gid=1000,nobrl,vers=3.0"
      o: "username=robbo,password=atilla1atilla1,uid=1000,gid=1000,nobrl,vers=3.0,file_mode=0777,dir_mode=0777"
      device: "//192.168.150.100/Documents"
