services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOTNET_SYSTEM_NET_DISABLEIPV6=1
      - JELLYFIN_PublishedServerUrl=http://localhost:8096
      - JELLYFIN_EnableDlna=false
    command: sh -c "sleep 15 && /jellyfin/jellyfin"
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
#      - /home/robbo/docker/jellyfin/config:/config
#      - /home/robbo/docker/jellyfin/cache:/cache
      - /mnt/media/git/rwp_docker/docker/jellyfin/config:/config
      - /mnt/media/git/rwp_docker/docker/jellyfin/cache:/cache
      - /media:/media
    networks:
      - tv-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped


  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
    #  - /home/robbo/docker/sonarr/config:/config
      - /mnt/media/git/rwp_docker/docker/sonarr/config:/config
      - /media/tv:/tv
      - /media/downloads:/downloads
    depends_on:
      sabnzbd:
        condition: service_healthy
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
    #  - /home/robbo/docker/radarr/config:/config
      - /mnt/media/git/rwp_docker/docker/radarr/config:/config
      - /sonarr/config:/config
      - /media/Xmovies:/movies
      - /media/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

#  jellyseerr:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
#    image: fallenbagel/jellyseerr:latest
#    container_name: jellyseerr
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
    ports:
      - "5055:5055"
    volumes:
   #   - /home/robbo/docker/jellyseerr/config:/app/config
      - /mnt/media/git/rwp_docker/docker/jellyseerr/config:/app/config
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api?mode=version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - /home/robbo/docker/sabnzbd/config:/config
      - /media/downloads:/downloads
    ports:
      - "8080:8080"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - "9696:9696"
    volumes:
  #    - /home/robbo/docker/prowlarr/config:/config
      - /mnt/media/git/rwp_docker/docker/prowlarr/config:/config
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
#      - /home/robbo/docker/qbittorrent/appdata:/config
      - /mnt/media/git/rwp_docker/docker/qbittorrent/appdata:/config
      - /media/Xmovies:/movies
      - /media/downloads:/downloads
    ports:
      - "8081:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
  #    - /home/robbo/docker/nzbget/config:/config
      - /mnt/media/git/rwp_docker/docker/nzbget/config:/config
      - /media/Xmovies:/movies
      - /media/downloads:/downloads
    ports:
      - "6789:6789"
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
#      - /home/robbo/docker/deluge/config:/config
      - /mnt/media/git/rwp_docker/docker/deluge/config:/config
      - /media/downloads:/downloads
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58846:58846/udp"
      - "6882:6881"
      - "6882:6881/udp"
    restart: unless-stopped


networks:
  tv-network:
    driver: bridge

volumes:
  ollama-data:
  open-webui-data:
  model-cache:
  pgdata:
  redisdata:
  paperless_consume:
    driver: local
    driver_opts:
      type: cifs
#      o: "username=robbo,password=atilla1atilla1,uid=1000,gid=1000,nobrl,vers=3.0"
      o: "username=robbo,password=atilla1atilla1,uid=1000,gid=1000,nobrl,vers=3.0,file_mode=0777,dir_mode=0777"
      device: "//192.168.150.100/Documents"
